/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Minesweeper;

/**
 *
 * @author brendon
 */
public class ApplicationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationFrame
     */
    public ApplicationFrame() {
        initComponents();
        int width = 9;
        int height = 9;
        minefieldPanel.setLayout(new java.awt.GridLayout(width + 1, height + 1));
        javax.swing.JButton[][] buttons = new javax.swing.JButton[width][height];
        
        for (int x = 0; x < width + 1; x++) {
            for (int y = 0; y < height + 1; y++) {
                if (x % 2 == 1 && y == 0 || x % 2 == 0 && y == width) {
                    minefieldPanel.add(new javax.swing.JLabel("OUT"));
                } else {
                    minefieldPanel.add(new HexagonalButton());
                }
            }
        }
        /*
        for (javax.swing.JButton[] button : buttons) {
            for (javax.swing.JButton b : button) {
                //b = new javax.swing.JButton();
                b = new HexagonalButton();
                b.setBorderPainted(false);
                b.setPreferredSize(new java.awt.Dimension(5, 5));
                minefieldPanel.add(b);
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicationPanel = new javax.swing.JPanel();
        titleBarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        difficultyComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        gameTypeComboBox = new javax.swing.JComboBox<>();
        timerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        minefieldContainerPanel = new javax.swing.JPanel();
        minefieldPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        applicationPanel.setBackground(new java.awt.Color(51, 51, 51));

        titleBarPanel.setBackground(new java.awt.Color(9, 68, 109));
        titleBarPanel.setPreferredSize(new java.awt.Dimension(1000, 65));
        titleBarPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Difficulty:");
        titleBarPanel.add(jLabel3);
        jLabel3.setBounds(610, 20, 120, 30);

        difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Intermediate", "Expert" }));
        difficultyComboBox.setPreferredSize(new java.awt.Dimension(135, 30));
        titleBarPanel.add(difficultyComboBox);
        difficultyComboBox.setBounds(730, 20, 130, 30);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Minesweeper Game Type:");
        titleBarPanel.add(jLabel1);
        jLabel1.setBounds(110, 20, 300, 30);

        gameTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Hexagonal", "Colouring Problem" }));
        gameTypeComboBox.setPreferredSize(new java.awt.Dimension(173, 30));
        titleBarPanel.add(gameTypeComboBox);
        gameTypeComboBox.setBounds(410, 20, 150, 30);

        timerPanel.setBackground(new java.awt.Color(8, 128, 214));
        timerPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Score -");
        timerPanel.add(jLabel2);
        jLabel2.setBounds(470, 10, 90, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");
        timerPanel.add(jLabel4);
        jLabel4.setBounds(560, 10, 20, 30);

        minefieldContainerPanel.setBackground(new java.awt.Color(51, 51, 51));
        minefieldContainerPanel.setSize(new java.awt.Dimension(965, 653));

        minefieldPanel.setBackground(new java.awt.Color(51, 51, 51));
        minefieldPanel.setPreferredSize(new java.awt.Dimension(945, 632));
        minefieldPanel.setLayout(new java.awt.GridLayout(9, 9));
        minefieldContainerPanel.add(minefieldPanel);

        javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
        applicationPanel.setLayout(applicationPanelLayout);
        applicationPanelLayout.setHorizontalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(minefieldContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        applicationPanelLayout.setVerticalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addComponent(titleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(timerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(minefieldContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applicationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applicationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApplicationFrame frame = new ApplicationFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel applicationPanel;
    private javax.swing.JComboBox<String> difficultyComboBox;
    private javax.swing.JComboBox<String> gameTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel minefieldContainerPanel;
    private javax.swing.JPanel minefieldPanel;
    private javax.swing.JPanel timerPanel;
    private javax.swing.JPanel titleBarPanel;
    // End of variables declaration//GEN-END:variables
}
